---
- name: Install Mysql Server/Client
  apt: name={{ item }} state=present
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb

- name: Start MySQL service
  service: name=mysql state=started enabled=yes

- name: Create Application Database
  mysql_db: name=test1 state=present
  
- name: Create Application Database
  mysql_db: name=test2 state=present

- name: Create Database User
  mysql_user: name={{ item.login }}  password={{ item.pass }} priv={{ item.priv }} state=present
  with_items:
    - "{{ users }}"
    
- name: configurating
  copy:
    src: mysql.cnf
    dest: /etc/mysql/mysql.cnf
  notify: 
   - restart mysql
  




  