---
- hosts: all
  sudo: yes
  tasks:
  - name: Add an environment variable to the remote user's shell.
    lineinfile: dest=~/.profile regexp=^ENV_VAR= line=ENV_VAR=value
  - name: bla
    shell: "cat ~/.profile"
  - name: Get the value of the environment variable we just added.
    shell: 'echo $ENV_VAR'
    register: foo
  - name: Print the value of the environment variable.
    debug: msg="The variable is {{ foo.stdout }}"